Frontend kanban tasks.php (styled with internal CSS for now)
james-tyner/echo-meetings pull request #28
Opened 2019-03-05 22:47 UTC by angella-qian

2019-03-05 23:24 UTC, james-tyner requested changes
Um... it looks like this https://screenshots.firefox.com/lsCeSZ0319TmV0Rb/localhost

We can either try to fix it on its own or merge it and fix everything on every page at the end

2019-03-05 23:58 UTC, angella-qian commented
@james-tyner I think when I grabbed the files again some styles were edited and affected mine, does this work better?

2019-03-06 00:53 UTC, james-tyner requested changes

2019-03-06 00:53 UTC, james-tyner commented on tasks.php
> +			min-width: 260px;
Remove this min-width and try using percentage widths only. You could also do some sort of calculated width if you need to account for margins. You can try 33% as a starting point and adjust from there. With the fixed width, the cards are too wide for my screen size but look perfect at the 15" screen size

**1280px screen**
![screen shot 2019-03-05 at 16 51 22](https://user-images.githubusercontent.com/45050998/53847828-020b7f00-3f67-11e9-8bc6-1945a2ab8775.png)

**1440px screen**
![screen shot 2019-03-05 at 16 51 17](https://user-images.githubusercontent.com/45050998/53847843-0d5eaa80-3f67-11e9-8d42-7e4a8e9e37da.png)

Eventually, we should create columns for the different categories of cards and set the widths on the columns rather than the cards themselves

2019-03-06 01:34 UTC, angella-qian commented on tasks.php
> +			min-width: 260px;
Oh I currently have widths set on the columns holding the cards (their ids are "not-started", "in-progress", and "complete"). The cards were showing up really long, so I shortened them with min-width.

2019-03-06 01:39 UTC, james-tyner commented on tasks.php
> +			min-width: 260px;
Oh so those are the ones that need to change!
```
#not-started, #in-progress, #complete {
	width: 325px;
```

2019-03-06 02:03 UTC, james-tyner approved these changes

2019-03-06 02:03 UTC, merged